# Generated by Django 4.1 on 2022-08-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('phone', models.CharField(max_length=11, null=True)),
                ('address', models.TextField()),
                ('images', models.ImageField(blank=True, upload_to='cinema_posters/', verbose_name='عکس ')),
            ],
            options={
                'verbose_name': 'cinema',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('poster', models.ImageField(upload_to='movie_posters/', verbose_name='پوستر')),
            ],
            options={
                'verbose_name': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('salable_seat', models.IntegerField()),
                ('free_seat', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'sale not started'), (2, 'sale open'), (3, 'sold out!'), (4, 'sale closed'), (5, 'movie played'), (6, 'shoe canceled!')])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.movie')),
            ],
        ),
    ]
